name: "Deploy Request to PROD Environment"
description: "This issue template is used to request a deployment to the PROD environment. Please ensure you have the necessary permissions and that the issue is labeled correctly."
title: "Trigger deployment to PROD"
body:
  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: "To be able to trigger the pipeline add label deploy-request-prod to the issue."
      options:
        - prod
    validations:
      required: true

  - type: dropdown
    id: team
    attributes:
      label: Team Name
      description: "Select the Team requesting this deployment. If you are not a member of the team, you will not be able to deploy."
      options:
        - prod
    validations:
      required: true
